#
# Crowdin CLI configuration for Website translations (zyra-website)
# See https://crowdin.github.io/crowdin-cli/configuration for more information
#

preserve_hierarchy: true
base_url: 'https://api.crowdin.com'
base_path: ..
languages_mapping:
  locale:
    fr: fr-FR

files:
  #
  # Source file - PO file for Lingui
  #
  - source: packages/zyra-website/src/locales/en.po
    #
    # Translation files path
    #
    translation: '%original_path%/%locale%.po'
