#
# Crowdin CLI configuration for App translations (zyra-front, zyra-server, zyra-emails)
# See https://crowdin.github.io/crowdin-cli/configuration for more information
#

preserve_hierarchy: true
base_path: ..

files:
  #
  # Source files filter - PO files for Lingui
  #
  - source: packages/zyra-front/src/locales/en.po
    #
    # Translation files path
    #
    translation: '%original_path%/%locale%.po'
  - source: packages/zyra-server/src/engine/core-modules/i18n/locales/en.po
    translation: '%original_path%/%locale%.po'
  - source: packages/zyra-emails/src/locales/en.po
    translation: '%original_path%/%locale%.po'
