apiVersion: v1
kind: PersistentVolume
metadata:
  name: zyracrm-server-pv
  namespace: zyracrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
