apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zyracrm-db-pvc
  namespace: zyracrm
spec:
  storageClassName: default
  volumeName: zyracrm-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
