apiVersion: v1
kind: Service
metadata:
  name: zyracrm-db
  namespace: zyracrm
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: zyracrm-db
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
