import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/zyra-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'zyra-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/zyra-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/zyra-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/zyra-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION } from 'src/modules/messaging/common/standard-objects/message-channel-message-association.workspace-entity';
import { MessageDirection } from 'src/modules/messaging/common/enums/message-direction.enum';

export const buildMessageChannelMessageAssociationStandardFlatFieldMetadatas =
  ({
    now,
    objectName,
    workspaceId,
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
  }: Omit<
    CreateStandardFieldArgs<
      'messageChannelMessageAssociation',
      FieldMetadataType
    >,
    'context'
  >): Record<
    AllStandardObjectFieldName<'messageChannelMessageAssociation'>,
    FlatFieldMetadata
  > => ({
    id: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'id',
        type: FieldMetadataType.UUID,
        label: i18nLabel(msg`Id`),
        description: i18nLabel(msg`Id`),
        icon: 'Icon123',
        isSystem: true,
        isNullable: false,
        isUIEditable: false,
        defaultValue: 'uuid',
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    createdAt: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'createdAt',
        type: FieldMetadataType.DATE_TIME,
        label: i18nLabel(msg`Data de criação`),
        description: i18nLabel(msg`Data de criação`),
        icon: 'IconCalendar',
        isSystem: true,
        isNullable: false,
        isUIEditable: false,
        defaultValue: 'now',
        settings: { displayFormat: DateDisplayFormat.RELATIVE },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    updatedAt: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'updatedAt',
        type: FieldMetadataType.DATE_TIME,
        label: i18nLabel(msg`Última atualização`),
        description: i18nLabel(msg`Última vez que o registro foi alterado`),
        icon: 'IconCalendarClock',
        isSystem: true,
        isNullable: false,
        isUIEditable: false,
        defaultValue: 'now',
        settings: { displayFormat: DateDisplayFormat.RELATIVE },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    deletedAt: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'deletedAt',
        type: FieldMetadataType.DATE_TIME,
        label: i18nLabel(msg`Excluído em`),
        description: i18nLabel(msg`Data em que o registro foi excluído`),
        icon: 'IconCalendarMinus',
        isSystem: true,
        isNullable: true,
        isUIEditable: false,
        settings: { displayFormat: DateDisplayFormat.RELATIVE },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    createdBy: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'createdBy',
        type: FieldMetadataType.ACTOR,
        label: i18nLabel(msg`Criado por`),
        description: i18nLabel(msg`O criador do registro`),
        icon: 'IconCreativeCommonsSa',
        isSystem: true,
        isUIEditable: false,
        isNullable: false,
        defaultValue: {
          source: "'MANUAL'",
          name: "'System'",
          workspaceMemberId: null,
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    updatedBy: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'updatedBy',
        type: FieldMetadataType.ACTOR,
        label: i18nLabel(msg`Atualizado por`),
        description: i18nLabel(
          msg`O membro do workspace que atualizou o registro por último`,
        ),
        icon: 'IconUserCircle',
        isSystem: true,
        isUIEditable: false,
        isNullable: false,
        defaultValue: {
          source: "'MANUAL'",
          name: "'System'",
          workspaceMemberId: null,
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    position: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'position',
        type: FieldMetadataType.POSITION,
        label: i18nLabel(msg`Posição`),
        description: i18nLabel(
          msg`Posição do registro da associação de mensagens do canal de mensagens`,
        ),
        icon: 'IconHierarchy2',
        isSystem: true,
        isNullable: false,
        defaultValue: 0,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    searchVector: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'searchVector',
        type: FieldMetadataType.TS_VECTOR,
        label: i18nLabel(msg`Vetor de busca`),
        description: i18nLabel(msg`Campo usado para busca de texto completo`),
        icon: 'IconUser',
        isSystem: true,
        isNullable: true,
        settings: {
          generatedType: 'STORED',
          asExpression: getTsVectorColumnExpressionFromFields(
            SEARCH_FIELDS_FOR_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION,
          ),
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    messageExternalId: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'messageExternalId',
        type: FieldMetadataType.TEXT,
        label: i18nLabel(msg`ID externo da mensagem`),
        description: i18nLabel(msg`ID da mensagem do provedor de mensagens`),
        icon: 'IconHash',
        isNullable: true,
        isUIEditable: false,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    messageThreadExternalId: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'messageThreadExternalId',
        type: FieldMetadataType.TEXT,
        label: i18nLabel(msg`ID externo da conversa`),
        description: i18nLabel(msg`ID da conversa do provedor de mensagens`),
        icon: 'IconHash',
        isNullable: true,
        isUIEditable: false,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    direction: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'direction',
        type: FieldMetadataType.SELECT,
        label: i18nLabel(msg`Direção`),
        description: i18nLabel(msg`Direção da mensagem`),
        icon: 'IconDirection',
        isNullable: false,
        isUIEditable: false,
        defaultValue: `'${MessageDirection.INCOMING}'`,
        options: [
          {
            id: '20202020-3075-4e35-b6a1-27db444a4668',
            value: MessageDirection.INCOMING,
            label: i18nLabel(msg`Recebida`),
            position: 0,
            color: 'green',
          },
          {
            id: '20202020-a15f-4512-9202-391a3c0bbed3',
            value: MessageDirection.OUTGOING,
            label: i18nLabel(msg`Enviada`),
            position: 1,
            color: 'blue',
          },
        ],
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    messageChannelId: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'messageChannelId',
        type: FieldMetadataType.UUID,
        label: i18nLabel(msg`ID do canal de mensagens`),
        description: i18nLabel(msg`ID do canal de mensagens`),
        icon: 'IconHash',
        isNullable: true,
        isUIEditable: false,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    messageThread: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'messageThread',
        label: i18nLabel(msg`ID da conversa da mensagem`),
        description: i18nLabel(msg`ID da conversa da mensagem`),
        icon: 'IconHash',
        isNullable: true,
        isUIEditable: false,
        targetObjectName: 'messageThread',
        targetFieldName: 'messageChannelMessageAssociations',
        settings: {
          relationType: RelationType.MANY_TO_ONE,
          onDelete: RelationOnDeleteAction.CASCADE,
          joinColumnName: 'messageThreadId',
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    message: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'message',
        label: i18nLabel(msg`ID da mensagem`),
        description: i18nLabel(msg`ID da mensagem`),
        icon: 'IconHash',
        isNullable: true,
        isUIEditable: false,
        targetObjectName: 'message',
        targetFieldName: 'messageChannelMessageAssociations',
        settings: {
          relationType: RelationType.MANY_TO_ONE,
          onDelete: RelationOnDeleteAction.CASCADE,
          joinColumnName: 'messageId',
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
    messageFolders: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'messageFolders',
        label: i18nLabel(msg`Pastas de mensagens`),
        description: i18nLabel(
          msg`Pastas de mensagens (suporta múltiplas pastas/rótulos)`,
        ),
        icon: 'IconFolders',
        isNullable: true,
        isUIEditable: false,
        targetObjectName: 'messageChannelMessageAssociationMessageFolder',
        targetFieldName: 'messageChannelMessageAssociation',
        settings: {
          relationType: RelationType.ONE_TO_MANY,
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      zyraStandardApplicationId,
      now,
    }),
  });
