import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/zyra-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  NumberDataType,
  RelationType,
} from 'zyra-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/zyra-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/zyra-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/zyra-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import {
  SEARCH_FIELDS_FOR_WORKSPACE_MEMBER,
  WorkspaceMemberNumberFormatEnum,
} from 'src/modules/workspace-member/standard-objects/workspace-member.workspace-entity';

export const buildWorkspaceMemberStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  zyraStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'workspaceMember', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'workspaceMember'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Data de criação`),
      description: i18nLabel(msg`Data de criação`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Última atualização`),
      description: i18nLabel(msg`Última vez que o registro foi alterado`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Excluído em`),
      description: i18nLabel(msg`Data em que o registro foi excluído`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Posição`),
      description: i18nLabel(msg`Posição do membro do workspace`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.FULL_NAME,
      label: i18nLabel(msg`Nome`),
      description: i18nLabel(msg`Nome do membro do workspace`),
      icon: 'IconCircleUser',
      isNullable: false,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  colorScheme: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'colorScheme',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Esquema de cores`),
      description: i18nLabel(msg`Esquema de cores preferido`),
      icon: 'IconColorSwatch',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'System'",
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  locale: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'locale',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Idioma`),
      description: i18nLabel(msg`Idioma preferido`),
      icon: 'IconLanguage',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'en'",
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  avatarUrl: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'avatarUrl',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`URL do avatar`),
      description: i18nLabel(msg`Avatar do membro do workspace`),
      icon: 'IconFileUpload',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  userEmail: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'userEmail',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`E-mail do usuário`),
      description: i18nLabel(msg`Endereço de e-mail do usuário relacionado`),
      icon: 'IconMail',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      isUnique: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  calendarStartDay: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'calendarStartDay',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Início da semana`),
      description: "User's preferred start day of the week",
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 7,
      settings: {
        dataType: NumberDataType.INT,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  userId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'userId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`ID do usuário`),
      description: i18nLabel(msg`ID do usuário associado`),
      icon: 'IconCircleUsers',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  timeZone: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'timeZone',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Fuso horário`),
      description: i18nLabel(msg`Fuso horário do usuário`),
      icon: 'IconTimezone',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'system'",
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  dateFormat: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dateFormat',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Formato de data`),
      description: "User's preferred date format",
      icon: 'IconCalendarEvent',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'SYSTEM'",
      options: [
        {
          id: '20202020-4b6a-4a08-8506-09bd59ef118e',
          value: 'SYSTEM',
          label: i18nLabel(msg`Sistema`),
          position: 0,
          color: 'turquoise',
        },
        {
          id: '20202020-6981-4e21-bb11-43ac1081be04',
          value: 'MONTH_FIRST',
          label: i18nLabel(msg`Mês primeiro`),
          position: 1,
          color: 'red',
        },
        {
          id: '20202020-bf56-4199-b013-27ee921d046d',
          value: 'DAY_FIRST',
          label: i18nLabel(msg`Dia primeiro`),
          position: 2,
          color: 'purple',
        },
        {
          id: '20202020-fd23-47d3-b01d-0479c11e5a2d',
          value: 'YEAR_FIRST',
          label: i18nLabel(msg`Ano primeiro`),
          position: 3,
          color: 'sky',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  timeFormat: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'timeFormat',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Formato de hora`),
      description: "User's preferred time format",
      icon: 'IconClock2',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'SYSTEM'",
      options: [
        {
          id: '20202020-349f-4ff8-82be-3eb52e7ec5f5',
          value: 'SYSTEM',
          label: i18nLabel(msg`Sistema`),
          position: 0,
          color: 'sky',
        },
        {
          id: '20202020-592c-4e33-a457-f4dcde59a3fc',
          value: 'HOUR_24',
          label: i18nLabel(msg`24HRS`),
          position: 1,
          color: 'red',
        },
        {
          id: '20202020-151c-43c2-a463-5bc42e5ce434',
          value: 'HOUR_12',
          label: i18nLabel(msg`12HRS`),
          position: 2,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  numberFormat: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'numberFormat',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Formato de número`),
      description: "User's preferred number format",
      icon: 'IconNumbers',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: `'${WorkspaceMemberNumberFormatEnum.SYSTEM}'`,
      options: [
        {
          id: '20202020-8b5b-4cee-8449-ca48d7c65c11',
          value: WorkspaceMemberNumberFormatEnum.SYSTEM,
          label: i18nLabel(msg`Sistema`),
          position: 0,
          color: 'turquoise',
        },
        {
          id: '20202020-657d-409b-9c2a-d8c3b8842859',
          value: WorkspaceMemberNumberFormatEnum.COMMAS_AND_DOT,
          label: i18nLabel(msg`Vírgulas e ponto`),
          position: 1,
          color: 'blue',
        },
        {
          id: '20202020-8703-4475-a92b-42e631851d8b',
          value: WorkspaceMemberNumberFormatEnum.SPACES_AND_COMMA,
          label: i18nLabel(msg`Espaços e vírgula`),
          position: 2,
          color: 'green',
        },
        {
          id: '20202020-2ea4-4b99-b72b-bebac01fd7db',
          value: WorkspaceMemberNumberFormatEnum.DOTS_AND_COMMA,
          label: i18nLabel(msg`Pontos e vírgula`),
          position: 3,
          color: 'orange',
        },
        {
          id: '20202020-9d07-4353-8ce9-d067d639abf5',
          value: WorkspaceMemberNumberFormatEnum.APOSTROPHE_AND_DOT,
          label: i18nLabel(msg`Apóstrofo e ponto`),
          position: 4,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Vetor de busca`),
      description: i18nLabel(msg`Campo usado para busca de texto completo`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_FOR_WORKSPACE_MEMBER,
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  assignedTasks: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'assignedTasks',
      label: i18nLabel(msg`Tarefas atribuídas`),
      description: i18nLabel(msg`Tarefas atribuídas ao membro do workspace`),
      icon: 'IconCheckbox',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'task',
      targetFieldName: 'assignee',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  accountOwnerForCompanies: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'accountOwnerForCompanies',
      label: i18nLabel(msg`Responsável pela conta das empresas`),
      description: i18nLabel(msg`Responsável pela conta das empresas`),
      icon: 'IconBriefcase',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'company',
      targetFieldName: 'accountOwner',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  messageParticipants: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'messageParticipants',
      label: i18nLabel(msg`Participantes da mensagem`),
      description: i18nLabel(msg`Participantes da mensagem`),
      icon: 'IconUserCircle',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'messageParticipant',
      targetFieldName: 'workspaceMember',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  blocklist: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'blocklist',
      label: i18nLabel(msg`Lista de bloqueio`),
      description: i18nLabel(msg`Contatos bloqueados`),
      icon: 'IconForbid2',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'blocklist',
      targetFieldName: 'workspaceMember',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  calendarEventParticipants: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'calendarEventParticipants',
      label: i18nLabel(msg`Participantes do evento de calendário`),
      description: i18nLabel(msg`Participantes do evento de calendário`),
      icon: 'IconCalendar',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'calendarEventParticipant',
      targetFieldName: 'workspaceMember',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: i18nLabel(msg`Eventos`),
      description: i18nLabel(msg`Eventos vinculados ao membro do workspace`),
      icon: 'IconTimelineEvent',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'workspaceMember',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  ownedOpportunities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'ownedOpportunities',
      label: i18nLabel(msg`Oportunidades sob responsabilidade`),
      description: i18nLabel(msg`Oportunidades sob responsabilidade do membro do workspace`),
      icon: 'IconTargetArrow',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'opportunity',
      targetFieldName: 'owner',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Criado por`),
      description: i18nLabel(msg`O criador do registro`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Atualizado por`),
      description: i18nLabel(
        msg`O membro do workspace que atualizou o registro por último`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    zyraStandardApplicationId,
    now,
  }),
});
