name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

env:
  ZYRA_VERSION: latest

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spawn Zyra test instance
        id: zyra
        uses: zyrahq/zyra/.github/actions/spawn-zyra-app-dev-test@main
        with:
          zyra-version: ${{ env.ZYRA_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run integration tests
        run: yarn test
        env:
          ZYRA_API_URL: ${{ steps.zyra.outputs.server-url }}
          ZYRA_API_KEY: ${{ steps.zyra.outputs.api-key }}
