import { Global, Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';

import {
  ConfigVariables,
  validate,
} from 'src/engine/core-modules/zyra-config/config-variables';
import { CONFIG_VARIABLES_INSTANCE_TOKEN } from 'src/engine/core-modules/zyra-config/constants/config-variables-instance-tokens.constants';
import { EnvironmentConfigDriver } from 'src/engine/core-modules/zyra-config/drivers/environment-config.driver';

@Global()
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      expandVariables: true,
      validate,
      // .env.brand is generated by scripts/select-brand.mjs and listed first
      // so brand-derived identity (product name, sender, logo, legal text)
      // wins over .env for the same keys; it's gitignored and absent unless
      // a brand has been selected, so this is a no-op otherwise.
      envFilePath:
        process.env.NODE_ENV === 'test'
          ? '.env.test'
          : ['.env.brand', '.env'],
    }),
  ],
  providers: [
    EnvironmentConfigDriver,
    {
      provide: CONFIG_VARIABLES_INSTANCE_TOKEN,
      useValue: new ConfigVariables(),
    },
  ],
  exports: [EnvironmentConfigDriver],
})
export class EnvironmentModule {}
